//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//


package edu.iris.station.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to SEED blockette 57.
 * 
 * <p>Java class for DecimationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecimationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InputSampleRate" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/>
 *         &lt;element name="Factor" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Offset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Delay" type="{http://www.fdsn.org/xml/station/1}FloatType"/>
 *         &lt;element name="Correction" type="{http://www.fdsn.org/xml/station/1}FloatType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecimationType", propOrder = {
    "inputSampleRate",
    "factor",
    "offset",
    "delay",
    "correction"
})
public class Decimation implements ResponseType{

    @XmlElement(name = "InputSampleRate", required = true)
    protected Frequency inputSampleRate;
    @XmlElement(name = "Factor", required = true)
    protected BigInteger factor;
    @XmlElement(name = "Offset", required = true)
    protected BigInteger offset;
    @XmlElement(name = "Delay", required = true)
    protected FloatType delay;
    @XmlElement(name = "Correction", required = true)
    protected FloatType correction;

    /**
     * Gets the value of the inputSampleRate property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getInputSampleRate() {
        return inputSampleRate;
    }

    /**
     * Sets the value of the inputSampleRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setInputSampleRate(Frequency value) {
        this.inputSampleRate = value;
    }

    /**
     * Gets the value of the factor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFactor() {
        return factor;
    }

    /**
     * Sets the value of the factor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFactor(BigInteger value) {
        this.factor = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffset(BigInteger value) {
        this.offset = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * @return
     *     possible object is
     *     {@link FloatType }
     *     
     */
    public FloatType getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link FloatType }
     *     
     */
    public void setDelay(FloatType value) {
        this.delay = value;
    }

    /**
     * Gets the value of the correction property.
     * 
     * @return
     *     possible object is
     *     {@link FloatType }
     *     
     */
    public FloatType getCorrection() {
        return correction;
    }

    /**
     * Sets the value of the correction property.
     * 
     * @param value
     *     allowed object is
     *     {@link FloatType }
     *     
     */
    public void setCorrection(FloatType value) {
        this.correction = value;
    }

	@Override
	public String getName() {
		return "Decimation";
	}

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return null;
	}

}
