//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//


package edu.iris.station.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type for longitude coordinate.
 * 
 * <p>Java class for LongitudeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LongitudeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>LongitudeBaseType">
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="WGS84" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LongitudeType")
public class Longitude
    extends LongitudeBaseType
{

    @XmlAttribute(name = "datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datum;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        if (datum == null) {
            return "WGS84";
        } else {
            return datum;
        }
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

	@Override
	public String toString() {
		return "Longitude [datum=" + datum + ", value=" + value + ", unit=" + unit + ", plusError=" + plusError
				+ ", minusError=" + minusError + ", measurementMethod=" + measurementMethod + "]";
	}

}
