//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//

package edu.iris.station.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * This type represents the Network layer, all station metadata is contained
 * within this element. The official name of the network or other descriptive
 * information can be included in the Description element. The Network can
 * contain 0 or more Stations.
 * 
 * <p>
 * Java class for NetworkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseNodeType">
 *       &lt;sequence>
 *         &lt;element name="Operator" type="{http://www.fdsn.org/xml/station/1}OperatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TotalNumberStations" type="{http://www.fdsn.org/xml/station/1}CounterType" minOccurs="0"/>
 *         &lt;element name="SelectedNumberStations" type="{http://www.fdsn.org/xml/station/1}CounterType" minOccurs="0"/>
 *         &lt;element name="Station" type="{http://www.fdsn.org/xml/station/1}StationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkType", propOrder = { "operator", "totalNumberStations", "selectedNumberStations", "stations" })
public class Network extends BaseNodeType {

	@XmlElement(name = "Operator")
	protected List<Operator> operator;
	@XmlElement(name = "TotalNumberStations")
	protected BigInteger totalNumberStations;
	@XmlElement(name = "SelectedNumberStations")
	protected BigInteger selectedNumberStations;
	@XmlElement(name = "Station")
	protected List<Station> stations=new ArrayList<>();

	@XmlTransient
	private FDSNStationXML rootDocument;

	@XmlTransient
	private long id;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setRootDocument(FDSNStationXML rootDocument) {
		this.rootDocument = rootDocument;
	}

	public void afterUnmarshal(Unmarshaller u, Object parent) {
		this.rootDocument = (FDSNStationXML) parent;
	}

	/**
	 * Gets the value of the operator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the operator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOperator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Operator }
	 * 
	 * 
	 */
	public List<Operator> getOperator() {
		if (operator == null) {
			operator = new ArrayList<Operator>();
		}
		return this.operator;
	}

	/**
	 * Gets the value of the totalNumberStations property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getTotalNumberStations() {
		return totalNumberStations;
	}

	/**
	 * Sets the value of the totalNumberStations property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setTotalNumberStations(BigInteger value) {
		this.totalNumberStations = value;
	}

	/**
	 * Gets the value of the selectedNumberStations property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSelectedNumberStations() {
		return selectedNumberStations;
	}

	/**
	 * Sets the value of the selectedNumberStations property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setSelectedNumberStations(BigInteger value) {
		this.selectedNumberStations = value;
	}

	/**
	 * Gets the value of the station property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the station property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getStation().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Station }
	 * 
	 * 
	 */

	public List<Station> getStations() {
		if (this.stations == null) {
			return Collections.emptyList();
		}
		return this.stations;
	}

	public void addStation(Station station) {
		if (station == null) {
			return;
		}
		station.setNetwork(this);
		this.stations.add(station);
	}

	public void addStations(List<Station> stations) {
		if (stations == null) {
			return;
		}
		if (this.stations == null) {
			this.stations = new ArrayList<>();
		}
		for (Station s : stations) {
			s.setNetwork(this);
			this.stations.add(s);
		}
	}

	public void merge(Station station) {
		if (station == null) {
			return;
		}

		if (this.stations == null) {
			this.stations = new ArrayList<>();
			this.addStation(station);
			return;
		}
		station.setNetwork(this);

		int index = this.stations.indexOf(station);

		if (index < 0) {
			this.addStation(station);
		} else {
			Station s = this.stations.get(index);
			for (Channel c : station.getChannels()) {
				s.merge(c);
			}
		}
	}
}
