//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//

package edu.iris.station.model;

import java.math.BigInteger;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * This type represents a Station epoch. It is common to only have a single
 * station epoch with the station's creation and termination dates as the epoch
 * start and end dates.
 * 
 * <p>
 * Java class for StationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="StationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseNodeType">
 *       &lt;sequence>
 *         &lt;element name="Latitude" type="{http://www.fdsn.org/xml/station/1}LatitudeType"/>
 *         &lt;element name="Longitude" type="{http://www.fdsn.org/xml/station/1}LongitudeType"/>
 *         &lt;element name="Elevation" type="{http://www.fdsn.org/xml/station/1}DistanceType"/>
 *         &lt;element name="Site" type="{http://www.fdsn.org/xml/station/1}SiteType"/>
 *         &lt;element name="WaterLevel" type="{http://www.fdsn.org/xml/station/1}FloatType" minOccurs="0"/>
 *         &lt;element name="Vault" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Geology" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Equipment" type="{http://www.fdsn.org/xml/station/1}EquipmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Operator" type="{http://www.fdsn.org/xml/station/1}OperatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="TerminationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="TotalNumberChannels" type="{http://www.fdsn.org/xml/station/1}CounterType" minOccurs="0"/>
 *         &lt;element name="SelectedNumberChannels" type="{http://www.fdsn.org/xml/station/1}CounterType" minOccurs="0"/>
 *         &lt;element name="ExternalReference" type="{http://www.fdsn.org/xml/station/1}ExternalReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Channel" type="{http://www.fdsn.org/xml/station/1}ChannelType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StationType", propOrder = { "latitude", "longitude", "elevation", "site", "waterLevel", "vault",
		"geology", "equipment", "operator", "creationDate", "terminationDate", "totalNumberChannels",
		"selectedNumberChannels", "externalReference", "channels" })
public class Station extends BaseNodeType {

	@XmlElement(name = "Latitude", required = true)
	protected Latitude latitude;
	@XmlElement(name = "Longitude", required = true)
	protected Longitude longitude;
	@XmlElement(name = "Elevation", required = true)
	protected Distance elevation;
	@XmlElement(name = "Site", required = true)
	protected Site site;
	@XmlElement(name = "WaterLevel")
	protected FloatType waterLevel;
	@XmlElement(name = "Vault")
	protected String vault;
	@XmlElement(name = "Geology")
	protected String geology;
	@XmlElement(name = "Equipment")
	protected List<Equipment> equipment;
	@XmlElement(name = "Operator")
	protected List<Operator> operator;
	@XmlElement(name = "CreationDate")
	@XmlJavaTypeAdapter(ZonedDateTimeXmlAdapter.class)
	protected ZonedDateTime creationDate;
	@XmlElement(name = "TerminationDate")
	@XmlJavaTypeAdapter(ZonedDateTimeXmlAdapter.class)
	protected ZonedDateTime terminationDate;
	@XmlElement(name = "TotalNumberChannels")
	protected BigInteger totalNumberChannels;
	@XmlElement(name = "SelectedNumberChannels")
	protected BigInteger selectedNumberChannels;
	@XmlElement(name = "ExternalReference")
	protected List<ExternalReferenceType> externalReference;
	@XmlElement(name = "Channel")
	protected List<Channel> channels = new ArrayList<>();

	@XmlTransient
	private Network network;

	@XmlTransient
	private long id;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void afterUnmarshal(Unmarshaller u, Object parent) {
		if (parent instanceof Network) {
			this.network = (Network) parent;
		} else {
			//
		}
	}

	public Network getNetwork() {
		return network;
	}

	public void setNetwork(Network network) {
		this.network = network;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return possible object is {@link Latitude }
	 * 
	 */
	public Latitude getLatitude() {
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value allowed object is {@link Latitude }
	 * 
	 */
	public void setLatitude(Latitude value) {
		this.latitude = value;
	}

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return possible object is {@link Longitude }
	 * 
	 */
	public Longitude getLongitude() {
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value allowed object is {@link Longitude }
	 * 
	 */
	public void setLongitude(Longitude value) {
		this.longitude = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link Distance }
	 * 
	 */
	public Distance getElevation() {
		return elevation;
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value allowed object is {@link Distance }
	 * 
	 */
	public void setElevation(Distance value) {
		this.elevation = value;
	}

	/**
	 * Gets the value of the site property.
	 * 
	 * @return possible object is {@link Site }
	 * 
	 */
	public Site getSite() {
		return site;
	}

	/**
	 * Sets the value of the site property.
	 * 
	 * @param value allowed object is {@link Site }
	 * 
	 */
	public void setSite(Site value) {
		this.site = value;
	}

	/**
	 * Gets the value of the waterLevel property.
	 * 
	 * @return possible object is {@link FloatType }
	 * 
	 */
	public FloatType getWaterLevel() {
		return waterLevel;
	}

	/**
	 * Sets the value of the waterLevel property.
	 * 
	 * @param value allowed object is {@link FloatType }
	 * 
	 */
	public void setWaterLevel(FloatType value) {
		this.waterLevel = value;
	}

	/**
	 * Gets the value of the vault property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVault() {
		return vault;
	}

	/**
	 * Sets the value of the vault property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setVault(String value) {
		this.vault = value;
	}

	/**
	 * Gets the value of the geology property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGeology() {
		return geology;
	}

	/**
	 * Sets the value of the geology property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setGeology(String value) {
		this.geology = value;
	}

	/**
	 * Gets the value of the equipment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the equipment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEquipment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Equipment }
	 * 
	 * 
	 */
	public List<Equipment> getEquipment() {
		if (equipment == null) {
			equipment = new ArrayList<>();
		}
		return this.equipment;
	}

	/**
	 * Gets the value of the operator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the operator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOperator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Operator }
	 * 
	 * 
	 */
	public List<Operator> getOperator() {
		if (operator == null) {
			operator = new ArrayList<>();
		}
		return this.operator;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public ZonedDateTime getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreationDate(ZonedDateTime value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the terminationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public ZonedDateTime getTerminationDate() {
		return terminationDate;
	}

	/**
	 * Sets the value of the terminationDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setTerminationDate(ZonedDateTime value) {
		this.terminationDate = value;
	}

	/**
	 * Gets the value of the totalNumberChannels property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getTotalNumberChannels() {
		return totalNumberChannels;
	}

	/**
	 * Sets the value of the totalNumberChannels property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setTotalNumberChannels(BigInteger value) {
		this.totalNumberChannels = value;
	}

	/**
	 * Gets the value of the selectedNumberChannels property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSelectedNumberChannels() {
		return selectedNumberChannels;
	}

	/**
	 * Sets the value of the selectedNumberChannels property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setSelectedNumberChannels(BigInteger value) {
		this.selectedNumberChannels = value;
	}

	/**
	 * Gets the value of the externalReference property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the externalReference property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExternalReference().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ExternalReferenceType }
	 * 
	 * 
	 */
	public List<ExternalReferenceType> getExternalReference() {
		if (externalReference == null) {
			externalReference = new ArrayList<>();
		}
		return this.externalReference;
	}

	/**
	 * Gets the value of the channel property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the channel property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getChannel().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Channel }
	 * 
	 * 
	 */
	public List<Channel> getChannels() {
		if (channels == null) {
			channels = new ArrayList<>();
		}
		return this.channels;
	}

	/*
	 * public void afterUnmarshal(Unmarshaller u, Object parent) { this.network =
	 * (Network) parent; }
	 */

	public void addChannel(Channel channel) {
		channel.setStation(this);
		if (this.channels == null) {
			this.channels = new ArrayList<Channel>();
		}
		this.channels.add(channel);
	}

	public void merge(Channel channel) {
		if (channel == null) {
			return;
		}

		int index = this.channels.indexOf(channel);
		if (index < 0) {
			this.channels.add(channel);
			return;
		}
		// if you get here, duplicate channels, so ignore
	}

	public void add(Comment comment) {
		if (comment == null) {
			return;
		}
		if (this.comment == null) {
			this.comment = new ArrayList<Comment>();
		}
		this.comment.add(comment);
	}

}
