//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//


package edu.iris.dmc.fdsn.station.model;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * A base node type for derivation from: Network, Station and Channel
 * 				types.
 * 
 * <p>Java class for BaseNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseNodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Identifier" type="{http://www.fdsn.org/xml/station/1}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comment" type="{http://www.fdsn.org/xml/station/1}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DataAvailability" type="{http://www.fdsn.org/xml/station/1}DataAvailabilityType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="sourceID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="restrictedStatus" type="{http://www.fdsn.org/xml/station/1}RestrictedStatusType" />
 *       &lt;attribute name="alternateCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="historicalCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseNodeType", propOrder = {
    "description",
    "identifier",
    "comment",
    "dataAvailability",
    "any"
})
@XmlSeeAlso({
    Station.class,
    Network.class,
    Channel.class
})
public class BaseNodeType {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Identifier")
    protected List<IdentifierType> identifier;
    @XmlElement(name = "Comment")
    protected List<Comment> comment;
    @XmlElement(name = "DataAvailability")
    protected DataAvailabilityType dataAvailability;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "code", required = true)
    protected String code;
    @XmlAttribute(name = "startDate")
    @XmlJavaTypeAdapter(ZonedDateTimeXmlAdapter.class)
	protected ZonedDateTime  startDate;
    @XmlAttribute(name = "endDate")
    @XmlJavaTypeAdapter(ZonedDateTimeXmlAdapter.class)
	protected ZonedDateTime endDate;
    @XmlAttribute(name = "sourceID")
    @XmlSchemaType(name = "anyURI")
    protected String sourceID;
    @XmlAttribute(name = "restrictedStatus")
    protected RestrictedStatusType restrictedStatus;
    @XmlAttribute(name = "alternateCode")
    protected String alternateCode;
    @XmlAttribute(name = "historicalCode")
    protected String historicalCode;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the dataAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link DataAvailabilityType }
     *     
     */
    public DataAvailabilityType getDataAvailability() {
        return dataAvailability;
    }

    /**
     * Sets the value of the dataAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataAvailabilityType }
     *     
     */
    public void setDataAvailability(DataAvailabilityType value) {
        this.dataAvailability = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public ZonedDateTime getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(ZonedDateTime value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public ZonedDateTime getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(ZonedDateTime value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the sourceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceID() {
        return sourceID;
    }

    /**
     * Sets the value of the sourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceID(String value) {
        this.sourceID = value;
    }

    /**
     * Gets the value of the restrictedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedStatusType }
     *     
     */
    public RestrictedStatusType getRestrictedStatus() {
        return restrictedStatus;
    }

    /**
     * Sets the value of the restrictedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedStatusType }
     *     
     */
    public void setRestrictedStatus(RestrictedStatusType value) {
        this.restrictedStatus = value;
    }

    /**
     * Gets the value of the alternateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCode() {
        return alternateCode;
    }

    /**
     * Sets the value of the alternateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCode(String value) {
        this.alternateCode = value;
    }

    /**
     * Gets the value of the historicalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistoricalCode() {
        return historicalCode;
    }

    /**
     * Sets the value of the historicalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistoricalCode(String value) {
        this.historicalCode = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

    public void addAttribute(QName qName,String value) {
		this.otherAttributes.put(qName, value);
	}
}
