//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//

package edu.iris.dmc.fdsn.station.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Equivalent to SEED blockette 52 and parent element for the related the
 * response blockettes.
 * 
 * <p>
 * Java class for ChannelType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ChannelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseNodeType">
 *       &lt;sequence>
 *         &lt;element name="ExternalReference" type="{http://www.fdsn.org/xml/station/1}ExternalReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Latitude" type="{http://www.fdsn.org/xml/station/1}LatitudeType"/>
 *         &lt;element name="Longitude" type="{http://www.fdsn.org/xml/station/1}LongitudeType"/>
 *         &lt;element name="Elevation" type="{http://www.fdsn.org/xml/station/1}DistanceType"/>
 *         &lt;element name="Depth" type="{http://www.fdsn.org/xml/station/1}DistanceType"/>
 *         &lt;element name="Azimuth" type="{http://www.fdsn.org/xml/station/1}AzimuthType" minOccurs="0"/>
 *         &lt;element name="Dip" type="{http://www.fdsn.org/xml/station/1}DipType" minOccurs="0"/>
 *         &lt;element name="WaterLevel" type="{http://www.fdsn.org/xml/station/1}FloatType" minOccurs="0"/>
 *         &lt;element name="Type" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="TRIGGERED"/>
 *               &lt;enumeration value="CONTINUOUS"/>
 *               &lt;enumeration value="HEALTH"/>
 *               &lt;enumeration value="GEOPHYSICAL"/>
 *               &lt;enumeration value="WEATHER"/>
 *               &lt;enumeration value="FLAG"/>
 *               &lt;enumeration value="SYNTHESIZED"/>
 *               &lt;enumeration value="INPUT"/>
 *               &lt;enumeration value="EXPERIMENTAL"/>
 *               &lt;enumeration value="MAINTENANCE"/>
 *               &lt;enumeration value="BEAM"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;group ref="{http://www.fdsn.org/xml/station/1}SampleRateGroup" minOccurs="0"/>
 *         &lt;element name="StorageFormat" type={http://www.w3.org/2001/XMLSchema-instance}"string" minOccurs="0">
 *         &lt;element name="ClockDrift" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.fdsn.org/xml/station/1>FloatType">
 *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SECONDS/SAMPLE" />
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CalibrationUnits" type="{http://www.fdsn.org/xml/station/1}UnitsType" minOccurs="0"/>
 *         &lt;element name="Sensor" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/>
 *         &lt;element name="PreAmplifier" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/>
 *         &lt;element name="DataLogger" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/>
 *         &lt;element name="Equipment" type="{http://www.fdsn.org/xml/station/1}EquipmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Response" type="{http://www.fdsn.org/xml/station/1}ResponseType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="locationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChannelType", propOrder = { "externalReference", "latitude", "longitude", "elevation", "depth",
		"azimuth", "dip", "waterLevel", "type", "sampleRate", "sampleRateRatio", "storageFormat", "clockDrift", "calibrationUnits",
		"sensor", "preAmplifier", "dataLogger", "equipment", "response" })
public class Channel extends BaseNodeType {

	@XmlElement(name = "ExternalReference")
	protected List<ExternalReferenceType> externalReference;
	@XmlElement(name = "Latitude", required = true)
	protected Latitude latitude;
	@XmlElement(name = "Longitude", required = true)
	protected Longitude longitude;
	@XmlElement(name = "Elevation", required = true)
	protected Distance elevation;
	@XmlElement(name = "Depth", required = true)
	protected Distance depth;
	@XmlElement(name = "Azimuth")
	protected Azimuth azimuth;
	@XmlElement(name = "Dip")
	protected Dip dip;
	@XmlElement(name = "WaterLevel")
	protected FloatType waterLevel;
	@XmlElement(name = "Type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected List<String> type;
	@XmlElement(name = "SampleRate")
	protected SampleRate sampleRate;
	@XmlElement(name = "SampleRateRatio")
	protected SampleRateRatioType sampleRateRatio;
	@XmlElement(name = "ClockDrift")
	protected Channel.ClockDrift clockDrift;
	@XmlElement(name = "CalibrationUnits")
	protected Units calibrationUnits;
	@XmlElement(name = "Sensor")
	protected Equipment sensor;
	@XmlElement(name = "PreAmplifier")
	protected Equipment preAmplifier;
	@XmlElement(name = "DataLogger")
	protected Equipment dataLogger;
	@XmlElement(name = "Equipment")
	protected List<Equipment> equipment;
	@XmlElement(name = "Response")
	protected Response response;
	@XmlElement(name = "StorageFormat")
	protected String storageFormat;
	@XmlAttribute(name = "locationCode", required = true)
	protected String locationCode;

	@XmlTransient
	private Station station;

	@XmlTransient
	private long id;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void afterUnmarshal(Unmarshaller u, Object parent) {
		this.station = (Station) parent;
	}
	
	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	/**
	 * Gets the value of the externalReference property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the externalReference property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExternalReference().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ExternalReferenceType }
	 * 
	 * 
	 */
	public List<ExternalReferenceType> getExternalReference() {
		if (externalReference == null) {
			externalReference = new ArrayList<ExternalReferenceType>();
		}
		return this.externalReference;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return possible object is {@link Latitude }
	 * 
	 */
	public Latitude getLatitude() {
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value allowed object is {@link Latitude }
	 * 
	 */
	public void setLatitude(Latitude value) {
		this.latitude = value;
	}

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return possible object is {@link Longitude }
	 * 
	 */
	public Longitude getLongitude() {
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value allowed object is {@link Longitude }
	 * 
	 */
	public void setLongitude(Longitude value) {
		this.longitude = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link Distance }
	 * 
	 */
	public Distance getElevation() {
		return elevation;
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value allowed object is {@link Distance }
	 * 
	 */
	public void setElevation(Distance value) {
		this.elevation = value;
	}

	/**
	 * Gets the value of the depth property.
	 * 
	 * @return possible object is {@link Distance }
	 * 
	 */
	public Distance getDepth() {
		return depth;
	}

	/**
	 * Sets the value of the depth property.
	 * 
	 * @param value allowed object is {@link Distance }
	 * 
	 */
	public void setDepth(Distance value) {
		this.depth = value;
	}

	/**
	 * Gets the value of the azimuth property.
	 * 
	 * @return possible object is {@link Azimuth }
	 * 
	 */
	public Azimuth getAzimuth() {
		return azimuth;
	}

	/**
	 * Sets the value of the azimuth property.
	 * 
	 * @param value allowed object is {@link Azimuth }
	 * 
	 */
	public void setAzimuth(Azimuth value) {
		this.azimuth = value;
	}

	/**
	 * Gets the value of the dip property.
	 * 
	 * @return possible object is {@link Dip }
	 * 
	 */
	public Dip getDip() {
		return dip;
	}

	/**
	 * Sets the value of the dip property.
	 * 
	 * @param value allowed object is {@link Dip }
	 * 
	 */
	public void setDip(Dip value) {
		this.dip = value;
	}

	/**
	 * Gets the value of the waterLevel property.
	 * 
	 * @return possible object is {@link FloatType }
	 * 
	 */
	public FloatType getWaterLevel() {
		return waterLevel;
	}

	/**
	 * Sets the value of the waterLevel property.
	 * 
	 * @param value allowed object is {@link FloatType }
	 * 
	 */
	public void setWaterLevel(FloatType value) {
		this.waterLevel = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the type property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getType() {
		return this.type == null ? Collections.EMPTY_LIST : this.type;
	}

	public void setType(List<String> type) {
		this.type = type;
	}

	/**
	 * Gets the value of the sampleRate property.
	 * 
	 * @return possible object is {@link SampleRate }
	 * 
	 */
	public SampleRate getSampleRate() {
		return sampleRate;
	}

	/**
	 * Sets the value of the sampleRate property.
	 * 
	 * @param value allowed object is {@link SampleRate }
	 * 
	 */
	public void setSampleRate(SampleRate value) {
		this.sampleRate = value;
	}

	/**
	 * Gets the value of the sampleRateRatio property.
	 * 
	 * @return possible object is {@link SampleRateRatioType }
	 * 
	 */
	public SampleRateRatioType getSampleRateRatio() {
		return sampleRateRatio;
	}

	/**
	 * Sets the value of the sampleRateRatio property.
	 * 
	 * @param value allowed object is {@link SampleRateRatioType }
	 * 
	 */
	public void setSampleRateRatio(SampleRateRatioType value) {
		this.sampleRateRatio = value;
	}

	/**
	 * Gets the value of the clockDrift property.
	 * 
	 * @return possible object is {@link Channel.ClockDrift }
	 * 
	 */
	public Channel.ClockDrift getClockDrift() {
		return clockDrift;
	}

	/**
	 * Sets the value of the clockDrift property.
	 * 
	 * @param value allowed object is {@link Channel.ClockDrift }
	 * 
	 */
	public void setClockDrift(Channel.ClockDrift value) {
		this.clockDrift = value;
	}

	/**
	 * Gets the value of the calibrationUnits property.
	 * 
	 * @return possible object is {@link Units }
	 * 
	 */
	public Units getCalibrationUnits() {
		return calibrationUnits;
	}

	/**
	 * Sets the value of the calibrationUnits property.
	 * 
	 * @param value allowed object is {@link Units }
	 * 
	 */
	public void setCalibrationUnits(Units value) {
		this.calibrationUnits = value;
	}

	/**
	 * Gets the value of the sensor property.
	 * 
	 * @return possible object is {@link Equipment }
	 * 
	 */
	public Equipment getSensor() {
		return sensor;
	}

	/**
	 * Sets the value of the sensor property.
	 * 
	 * @param value allowed object is {@link Equipment }
	 * 
	 */
	public void setSensor(Equipment value) {
		this.sensor = value;
	}

	/**
	 * Gets the value of the preAmplifier property.
	 * 
	 * @return possible object is {@link Equipment }
	 * 
	 */
	public Equipment getPreAmplifier() {
		return preAmplifier;
	}

	/**
	 * Sets the value of the preAmplifier property.
	 * 
	 * @param value allowed object is {@link Equipment }
	 * 
	 */
	public void setPreAmplifier(Equipment value) {
		this.preAmplifier = value;
	}

	/**
	 * Gets the value of the dataLogger property.
	 * 
	 * @return possible object is {@link Equipment }
	 * 
	 */
	public Equipment getDataLogger() {
		return dataLogger;
	}

	/**
	 * Sets the value of the dataLogger property.
	 * 
	 * @param value allowed object is {@link Equipment }
	 * 
	 */
	public void setDataLogger(Equipment value) {
		this.dataLogger = value;
	}

	/**
	 * Gets the value of the equipment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the equipment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEquipment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Equipment }
	 * 
	 * 
	 */
	public List<Equipment> getEquipment() {
		if (equipment == null) {
			equipment = new ArrayList<>();
		}
		return this.equipment;
	}

	/**
	 * Gets the value of the response property.
	 * 
	 * @return possible object is {@link Response }
	 * 
	 */
	public Response getResponse() {
		return response;
	}

	/**
	 * Sets the value of the response property.
	 * 
	 * @param value allowed object is {@link Response }
	 * 
	 */
	public void setResponse(Response value) {
		this.response = value;
	}

	/**
	 * Gets the value of the storage format property.
	 * 
	 * @return possible object is {@link Channel.StorageFormat }
	 * 
	 */
	public String getStorageformat() {
		return storageFormat;
	}

	/**
	 * Sets the value of the storage property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	
	public void setStorageFormat(String value) {
		this.storageFormat = value;
	}
	/**
    * Gets the value of the locationCode property.
    * 
    * @return possible object is {@link String }
    * 
    */
	public String getLocationCode() {
		return locationCode;
	}

	/**
	 * Sets the value of the locationCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setLocationCode(String value) {
		this.locationCode = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;restriction base="&lt;http://www.fdsn.org/xml/station/1>FloatType">
	 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SECONDS/SAMPLE" />
	 *     &lt;/restriction>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class ClockDrift extends FloatType {

	}

	public void addType(String type) {

		if (this.type == null) {
			this.type = new ArrayList<>();
		}
		if (type == null) {
			return;
		}
		this.type.add(type);
	}

	public void add(Comment comment) {
		if (comment == null) {
			return;
		}
		if (this.comment == null) {
			this.comment = new ArrayList<Comment>();
		}
		this.comment.add(comment);
	}

	public void addStage(ResponseStage stage) {
		if (this.getResponse() == null) {
			this.response = new Response();
		}
		this.response.getStage().add(stage);
	}
}
