//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//


package edu.iris.dmc.fdsn.station.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Response: coefficients for FIR filter. Laplace transforms or IIR
 * 				filters can be expressed using type as well but the PolesAndZerosType should be used
 * 				instead. Corresponds to SEED blockette 54.
 * 
 * <p>Java class for CoefficientsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoefficientsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType">
 *       &lt;sequence>
 *         &lt;element name="CfTransferFunctionType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ANALOG (RADIANS/SECOND)"/>
 *               &lt;enumeration value="ANALOG (HERTZ)"/>
 *               &lt;enumeration value="DIGITAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Numerator" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>FloatNoUnitType">
 *                 &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Denominator" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>FloatNoUnitType">
 *                 &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoefficientsType", propOrder = {
    "cfTransferFunctionType",
    "numerator",
    "denominator"
})
public class Coefficients
    extends BaseFilter
{

    @XmlElement(name = "CfTransferFunctionType", required = true)
    protected String cfTransferFunctionType;
    @XmlElement(name = "Numerator")
    protected List<Coefficients.Numerator> numerator;
    @XmlElement(name = "Denominator")
    protected List<Coefficients.Denominator> denominator;

    /**
     * Gets the value of the cfTransferFunctionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfTransferFunctionType() {
        return cfTransferFunctionType;
    }

    /**
     * Sets the value of the cfTransferFunctionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfTransferFunctionType(String value) {
        this.cfTransferFunctionType = value;
    }

    /**
     * Gets the value of the numerator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numerator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumerator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coefficients.Numerator }
     * 
     * 
     */
    public List<Coefficients.Numerator> getNumerator() {
        if (numerator == null) {
            numerator = new ArrayList<>();
        }
        return this.numerator;
    }

    /**
     * Gets the value of the denominator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denominator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDenominator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coefficients.Denominator }
     * 
     * 
     */
    public List<Coefficients.Denominator> getDenominator() {
        if (denominator == null) {
            denominator = new ArrayList<>();
        }
        return this.denominator;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>FloatNoUnitType">
     *       &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Denominator
        extends FloatNoUnitType
    {

        @XmlAttribute(name = "number")
        protected BigInteger number;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumber(BigInteger value) {
            this.number = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>FloatNoUnitType">
     *       &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Numerator
        extends FloatNoUnitType
    {

        @XmlAttribute(name = "number")
        protected int number;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumber(int value) {
            this.number = value;
        }

    }

}
