//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 01:37:05 PM PDT 
//


package edu.iris.dmc.fdsn.station.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Response: expressed as a polynomial (allows non-linear sensors to be
 * 				described). Corresponds to SEED blockette 62. Can be used to describe a stage of
 * 				acquisition or a complete system. 
 * 
 * <p>Java class for PolynomialType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolynomialType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType">
 *       &lt;sequence>
 *         &lt;element name="ApproximationType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="MACLAURIN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FrequencyLowerBound" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/>
 *         &lt;element name="FrequencyUpperBound" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/>
 *         &lt;element name="ApproximationLowerBound" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ApproximationUpperBound" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MaximumError" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Coefficient" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>FloatNoUnitType">
 *                 &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolynomialType", propOrder = {
    "approximationType",
    "frequencyLowerBound",
    "frequencyUpperBound",
    "approximationLowerBound",
    "approximationUpperBound",
    "maximumError",
    "coefficient"
})
public class Polynomial
    extends BaseFilter
{

    @XmlElement(name = "ApproximationType", required = true, defaultValue = "MACLAURIN")
    protected String approximationType;
    @XmlElement(name = "FrequencyLowerBound", required = true)
    protected Frequency frequencyLowerBound;
    @XmlElement(name = "FrequencyUpperBound", required = true)
    protected Frequency frequencyUpperBound;
    @XmlElement(name = "ApproximationLowerBound")
    protected double approximationLowerBound;
    @XmlElement(name = "ApproximationUpperBound")
    protected double approximationUpperBound;
    @XmlElement(name = "MaximumError")
    protected double maximumError;
    @XmlElement(name = "Coefficient", required = true)
    protected List<Polynomial.Coefficient> coefficient;

    /**
     * Gets the value of the approximationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproximationType() {
        return approximationType;
    }

    /**
     * Sets the value of the approximationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproximationType(String value) {
        this.approximationType = value;
    }

    /**
     * Gets the value of the frequencyLowerBound property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getFrequencyLowerBound() {
        return frequencyLowerBound;
    }

    /**
     * Sets the value of the frequencyLowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setFrequencyLowerBound(Frequency value) {
        this.frequencyLowerBound = value;
    }

    /**
     * Gets the value of the frequencyUpperBound property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getFrequencyUpperBound() {
        return frequencyUpperBound;
    }

    /**
     * Sets the value of the frequencyUpperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setFrequencyUpperBound(Frequency value) {
        this.frequencyUpperBound = value;
    }

    /**
     * Gets the value of the approximationLowerBound property.
     * 
     */
    public double getApproximationLowerBound() {
        return approximationLowerBound;
    }

    /**
     * Sets the value of the approximationLowerBound property.
     * 
     */
    public void setApproximationLowerBound(double value) {
        this.approximationLowerBound = value;
    }

    /**
     * Gets the value of the approximationUpperBound property.
     * 
     */
    public double getApproximationUpperBound() {
        return approximationUpperBound;
    }

    /**
     * Sets the value of the approximationUpperBound property.
     * 
     */
    public void setApproximationUpperBound(double value) {
        this.approximationUpperBound = value;
    }

    /**
     * Gets the value of the maximumError property.
     * 
     */
    public double getMaximumError() {
        return maximumError;
    }

    /**
     * Sets the value of the maximumError property.
     * 
     */
    public void setMaximumError(double value) {
        this.maximumError = value;
    }

    /**
     * Gets the value of the coefficient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coefficient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoefficient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Polynomial.Coefficient }
     * 
     * 
     */
    public List<Polynomial.Coefficient> getCoefficient() {
        if (coefficient == null) {
            coefficient = new ArrayList<Polynomial.Coefficient>();
        }
        return this.coefficient;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1>FloatNoUnitType">
     *       &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Coefficient
        extends FloatNoUnitType
    {

        @XmlAttribute(name = "number")
        protected int number;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumber(int value) {
            this.number = value;
        }

    }

}
